version: "3.8"

services:
  luminai:
    build: .
    container_name: luminai
    ports:
      - "3000:3000"
      - "8000:8000"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
      - "8004:8004"
      - "5555:5555" # Prisma Studio
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:15
    restart: always
    container_name: luminai_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
